"""empty message

Revision ID: 5d3059d1eb3f
Revises: 
Create Date: 2026-07-11 13:01:24.929811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5d3059d1eb3f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nodes')
    op.drop_table('schema_version')
    op.drop_table('global_client_insights')
    op.drop_table('projects')
    op.drop_table('prompt_blueprints')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_blueprints',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('blueprint_name', sa.TEXT(), nullable=False),
    sa.Column('version_string', sa.TEXT(), nullable=False),
    sa.Column('master_prompt_text', sa.TEXT(), nullable=False),
    sa.Column('is_active', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('global_tags', sa.TEXT(), server_default=sa.text("'[]'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_client_insights',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('client_or_industry_tag', sa.TEXT(), nullable=False),
    sa.Column('observed_pattern', sa.TEXT(), nullable=False),
    sa.Column('frequency_count', sa.INTEGER(), server_default=sa.text('1'), nullable=False),
    sa.Column('last_updated', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_or_industry_tag', 'observed_pattern')
    )
    op.create_table('schema_version',
    sa.Column('version', sa.INTEGER(), nullable=False)
    )
    op.create_table('nodes',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('project_id', sa.TEXT(), nullable=False),
    sa.Column('parent_id', sa.TEXT(), nullable=True),
    sa.Column('layer_type', sa.TEXT(), nullable=False),
    sa.Column('node_name', sa.TEXT(), nullable=False),
    sa.Column('metadata_json', sa.TEXT(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('content_markdown', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.Column('version_tag', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
